// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Mentions Légales documents
 */
interface MentionsLegalesDocumentData {
  /**
   * Contenu field in *Mentions Légales*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mentions_legales.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Mentions Légales document from Prismic
 *
 * - **API ID**: `mentions_legales`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MentionsLegalesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MentionsLegalesDocumentData>,
    "mentions_legales",
    Lang
  >;

/**
 * Item in *Offre d'emploi → Technologies*
 */
export interface OffreEmploiDocumentDataTechnologiesItem {
  /**
   * Name field in *Offre d'emploi → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.technologies[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Item in *Offre d'emploi → Emails admin*
 */
export interface OffreEmploiDocumentDataAdminEmailsItem {
  /**
   * Email field in *Offre d'emploi → Emails admin*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.admin_emails[].email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;
}

/**
 * Content for Offre d'emploi documents
 */
interface OffreEmploiDocumentData {
  /**
   * Titre field in *Offre d'emploi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description courte field in *Offre d'emploi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_description: prismic.KeyTextField;

  /**
   * Contenu field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Technologies field in *Offre d'emploi*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.technologies[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  technologies: prismic.GroupField<
    Simplify<OffreEmploiDocumentDataTechnologiesItem>
  >;

  /**
   * Emails admin field in *Offre d'emploi*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: offre_emploi.admin_emails[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  admin_emails: prismic.GroupField<
    Simplify<OffreEmploiDocumentDataAdminEmailsItem>
  >;
}

/**
 * Offre d'emploi document from Prismic
 *
 * - **API ID**: `offre_emploi`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OffreEmploiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OffreEmploiDocumentData>,
    "offre_emploi",
    Lang
  >;

export type AllDocumentTypes = MentionsLegalesDocument | OffreEmploiDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      MentionsLegalesDocument,
      MentionsLegalesDocumentData,
      OffreEmploiDocument,
      OffreEmploiDocumentData,
      OffreEmploiDocumentDataTechnologiesItem,
      OffreEmploiDocumentDataAdminEmailsItem,
      AllDocumentTypes,
    };
  }
}
